language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - CODECOV_TOKEN='c2b06ef6-34d6-41ab-ab11-f27493f3bc1a'

install:
  - pip install -r requirements.txt

script: 
  - coverage run unittest_api.py

after_success: 
  - bash <(curl -s https://codecov.io/bash)