language: python

python:
  - "3.6.1"

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - coverage run unittest_webapp.py

after_success: 
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t group42/a2 .