language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script: 
  - coverage run unittest_webapp.py

after_success: 
  - bash <(curl -s https://codecov.io/bash)