language: python

python:
  - "3.6.1"

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - coverage run unittest_webapp.py

after_success: 
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t group42/a2 .
  - docker run -d -p 5000:5000 group42/a2 /bin/sh
  - docker ps -a

deploy:
  provider: elasticbeanstalk
  access_key_id: access-key-id
  secret_access_key:
    secure: "secret-access-key"
  region: "ca-central-1"  
  app: "elastic-beanstalk-helloworld"
  env: "elastic-beanstalk-helloworld-dev"
  bucket_name: "elasticbeanstalk-ca-central-helloworld"
  on:
    branch: main
    
after_deploy:
  - echo "done deploying"
